### ISSUE TITLE
Failed to load extensions on launch

### ISSUE THREAD

**Issue by Zetaphor** [exokitxr/metachromium#34]
Release: 0.0.7
OS: Windows 10 Home 1903
SteamVR: 1.9.16
Folder Path: C:\Users\Zetaphor\Desktop\Metachromium 0.0.7

Two errors appear when launching process.exe:
![image](https://user-images.githubusercontent.com/3112763/74561813-553bcf00-4f37-11ea-8451-6fff2f64a50f.png)
![image](https://user-images.githubusercontent.com/3112763/74561830-608efa80-4f37-11ea-96b1-a30709f8c280.png)

**Comment by avaer** [comment]
<img width="304" alt="Capture" src="https://user-images.githubusercontent.com/6926057/74562306-8537a200-4f38-11ea-87f0-a08e1dadcc03.PNG">

Reproduced. The relative paths must be being computed wrongly in the release.

Also I see `extension` in the release contents but not `metamask`.

<img width="200" alt="Capture" src="https://user-images.githubusercontent.com/6926057/74562405-bca64e80-4f38-11ea-9d9c-056324ff62c9.PNG">

**Comment by avaer** [comment]
Posterity: here are the build scripts:

https://github.com/exokitxr/metachromium/blob/master/build.ps1
https://github.com/exokitxr/metachromium/blob/master/device/vr/build.ps1

**Comment by Zetaphor** [comment]
Resolved with v0.0.8
