### ISSUE TITLE
File not found, host unreachable on launch

### ISSUE THREAD

**Issue by Zetaphor** [exokitxr/metachromium#39]
Release: 0.0.8
OS: Windows 10 Home 1903
SteamVR: 1.9.16
Headset: Quest with Virtual Desktop
Folder Path: D:\Metachromium 0.0.8

Launching process.exe launches Chrome window with two tabs:
![image](https://user-images.githubusercontent.com/3112763/74566508-9f29b280-4f41-11ea-939a-fd05af4d70d8.png)

![image](https://user-images.githubusercontent.com/3112763/74566528-a781ed80-4f41-11ea-97d6-9cd6c37317bf.png)

**Comment by avaer** [comment]
I just tried `v0.0.9` and on my machine it gets past this point.

The processes might still be interfering with each other on launch, which is a separate issue: https://github.com/exokitxr/metachromium/issues/41

**Comment by Zetaphor** [comment]
Still having seeing both errors on `v0.0.9`
![image](https://user-images.githubusercontent.com/3112763/74570186-267b2400-4f4a-11ea-9af8-3ea5bafce29f.png)

Verified all child processes were killed first

**Comment by avaer** [comment]
Thanks for checking, I'll look deeper.

**Comment by avaer** [comment]
Ah, this is probably because of the file path being split by a space. Will need to quote it.

**Comment by avaer** [comment]
I managed to launch in from `C:\Metachromium 0.0.8`, using the https://github.com/exokitxr/metachromium/releases/tag/v0.0.11 build.

<img width="1471" alt="Capture" src="https://user-images.githubusercontent.com/6926057/74575177-fa64a080-4f53-11ea-9c09-22c5dc8e75f3.PNG">

**Comment by Zetaphor** [comment]
Verified resolved
